# This is a basic workflow to help you get started with Actions

name: Quality Deployment

# Controls when the workflow will run
# Allows you to run this workflow manually from the Actions tab

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Enter SAP Release Version"
        required: true
        default: "SAP Release - x Quality Branch"
      reviewer:
        description: "Enter Reviewer Username"
        required: true
        default: ""
      pat:
        description: "Enter Personal Access Token"
        required: true
        default: ""
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Quality Changes Step
        uses: ./.github/actions/quality/
